/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view.screens.dialogs;

import controller.ProjetoController;
import model.entities.Cliente;
import model.entities.Projeto; 
import java.time.format.DateTimeFormatter; 
import model.entities.Usuario;
import java.util.List;
import javax.swing.JOptionPane;

/**
 * @author Viktin
 */
public class DlgCadastroProjetos extends javax.swing.JDialog {

    private final ProjetoController controller;
    private Projeto projetoEmEdicao = null;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DlgCadastroProjetos.class.getName());
    
    public DlgCadastroProjetos(java.awt.Frame parent, boolean modal, Usuario usuario) {
        super(parent, modal);
        initComponents();
        
        this.controller = new ProjetoController(this, usuario);
        
        this.setLocationRelativeTo(null);
    }
    
    public void setProjetoParaEdicao(Projeto p) {
        this.projetoEmEdicao = p;
        if (p != null) {
            controller.preencherCamposEdicao(p);
        }
    }
    public void setProjetoCampos(String nome, String desc, String status, String orcamento, String dataIn, String dataPrev, Cliente cliente) {
        edtNomeProjeto.setText(nome);
        edtDescricao.setText(desc);
        cbStatus.setSelectedItem(status);
        edtOrcamento.setText(orcamento);
        edtDataInicio.setText(dataIn);
        edtPrevisao.setText(dataPrev);

        // Para o JComboBox de Clientes selecionar o correto:
        if (cliente != null) {
            for (int i = 0; i < cbCliente.getItemCount(); i++) {
                Cliente item = cbCliente.getItemAt(i);
                if (item.getId().equals(cliente.getId())) {
                    cbCliente.setSelectedIndex(i);
                    break;
                }
            }
        }
    }
    public Projeto getProjetoEmEdicao() {
        return this.projetoEmEdicao;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        edtNomeProjeto = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        edtDataInicio = new javax.swing.JFormattedTextField();
        edtPrevisao = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        edtDescricao = new javax.swing.JTextArea();
        cbStatus = new javax.swing.JComboBox<>();
        edtOrcamento = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        cbCliente = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        edtNomeProjeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtNomeProjetoActionPerformed(evt);
            }
        });
        jPanel1.add(edtNomeProjeto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 280, -1));

        jLabel8.setText("Nome do Projeto:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jLabel2.setText("Cliente:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel5.setText("Data Início:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        edtDataInicio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        edtDataInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtDataInicioActionPerformed(evt);
            }
        });
        jPanel1.add(edtDataInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 129, -1));

        edtPrevisao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        jPanel1.add(edtPrevisao, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 129, -1));

        jLabel6.setText("Previsão:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, -1, -1));

        jLabel7.setText("Descrição / Observações");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        edtDescricao.setColumns(20);
        edtDescricao.setRows(5);
        jScrollPane1.setViewportView(edtDescricao);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 440, 110));

        cbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Em Andamento", "Concluido", "Pausado" }));
        cbStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbStatusActionPerformed(evt);
            }
        });
        jPanel1.add(cbStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, 130, -1));

        edtOrcamento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        jPanel1.add(edtOrcamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, 130, -1));

        jLabel4.setText("Orçamento (R$):");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, -1, -1));

        jLabel3.setText("Status:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, -1, -1));

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, 130, 30));

        cbCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbClienteActionPerformed(evt);
            }
        });
        jPanel1.add(cbCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 280, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbStatusActionPerformed

    private void edtNomeProjetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtNomeProjetoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtNomeProjetoActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        controller.salvarProjeto();
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void cbClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbClienteActionPerformed

    private void edtDataInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtDataInicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtDataInicioActionPerformed

    /**
     * @param args the command line arguments
     */
    public String getNome() {
        return edtNomeProjeto.getText();
    }

    public Cliente getClienteSelecionado() {
        // Cast seguro: O ComboBox guarda objetos do tipo Cliente
        return (Cliente) cbCliente.getSelectedItem();
    }

    public String getDataInicio() {
        return edtDataInicio.getText();
    }

    public String getDataPrevisao() {
        return edtPrevisao.getText();
    }

    public String getDescricao() {
        return edtDescricao.getText();
    }

    public String getOrcamento() {
        return edtOrcamento.getText();
    }

    public String getStatus() {
        return (String) cbStatus.getSelectedItem();
    }
    
    /**
     * Atualiza a lista de clientes disponiveis no ComboBox.
     * Chamado pelo Controller ao abrir a tela.
     */
    public void atualizarComboClientes(List<Cliente> listaClientes) {
        cbCliente.removeAllItems();
        for (Cliente c : listaClientes) {
            cbCliente.addItem(c);
        }
    }
    
    public void exibeMensagem(String msg) {
        JOptionPane.showMessageDialog(this, msg);
    }    
    
    public void limparCampos() {
        edtNomeProjeto.setText("");
        edtDescricao.setText("");
        edtOrcamento.setText("");
        edtDataInicio.setText("");
        edtPrevisao.setText("");
        // Reseta o combo para o primeiro item ou null
        if (cbCliente.getItemCount() > 0) cbCliente.setSelectedIndex(0);
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                DlgCadastroProjetos dialog = new DlgCadastroProjetos(new javax.swing.JFrame(), true, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<Cliente> cbCliente;
    private javax.swing.JComboBox<String> cbStatus;
    private javax.swing.JFormattedTextField edtDataInicio;
    private javax.swing.JTextArea edtDescricao;
    private javax.swing.JTextField edtNomeProjeto;
    private javax.swing.JFormattedTextField edtOrcamento;
    private javax.swing.JFormattedTextField edtPrevisao;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
