/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view.screens.dialogs;

import controller.DocumentoController;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import model.entities.Projeto;

/**
 * @author Viktin
 */
public class DlgCadastroDocumento extends javax.swing.JDialog {
    
    private final DocumentoController controller;
    private File arquivoSelecionado;
    private Projeto projetoVinculado;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DlgCadastroDocumento.class.getName());

    public DlgCadastroDocumento(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.controller = new DocumentoController();
        
        // Bloqueia edição manual para evitar caminhos inválidos (copy-paste errado do user)
        this.edtCaminhoArquivo.setEditable(false);
        this.setLocationRelativeTo(null);
    }
    
    public void setProjetoVinculado(Projeto p) {
        this.projetoVinculado = p;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        edtCaminhoArquivo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cbCategoriaDocumento = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        edtNomeDocumento = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnSelecionar = new javax.swing.JButton();
        btnSalvarDocumento = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        edtCaminhoArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtCaminhoArquivoActionPerformed(evt);
            }
        });
        jPanel1.add(edtCaminhoArquivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 290, -1));

        jLabel2.setText("Nome do Documento: ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        cbCategoriaDocumento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Legal", "terreno", "Executivo", "Contratos", "Financeiro" }));
        jPanel1.add(cbCategoriaDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 120, -1));

        jLabel3.setText("Categoria:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        edtNomeDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtNomeDocumentoActionPerformed(evt);
            }
        });
        jPanel1.add(edtNomeDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 430, -1));

        jLabel4.setText("Caminho do Arquivo:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        btnSelecionar.setText("Selecionar Arquivo...");
        btnSelecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelecionarActionPerformed(evt);
            }
        });
        jPanel1.add(btnSelecionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, -1, -1));

        btnSalvarDocumento.setText("Salvar");
        btnSalvarDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarDocumentoActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalvarDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 190));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void edtCaminhoArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtCaminhoArquivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtCaminhoArquivoActionPerformed

    private void edtNomeDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtNomeDocumentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtNomeDocumentoActionPerformed

    private void btnSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecionarActionPerformed
       // UX: Tenta forçar o visual nativo do sistema operacional para a janela de arquivos
        try {
            javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
            javax.swing.SwingUtilities.updateComponentTreeUI(this);
        } catch (Exception e) {
            // Falha silenciosa: se não der, usa o padrão do Java (Metal)
        }

        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Selecione o documento");
        
        // Filtro para guiar o usuário aos tipos corretos
        javax.swing.filechooser.FileNameExtensionFilter filtro = 
            new javax.swing.filechooser.FileNameExtensionFilter(
                "Arquivos de Projeto (PDF, Imagens, DWG)", "pdf", "jpg", "jpeg", "png", "dwg");
        fileChooser.setFileFilter(filtro);
        
        int retorno = fileChooser.showOpenDialog(this);
        
        if (retorno == JFileChooser.APPROVE_OPTION) {
            this.arquivoSelecionado = fileChooser.getSelectedFile();
            edtCaminhoArquivo.setText(this.arquivoSelecionado.getAbsolutePath());
            
            // Auto-fill: Se o user não digitou nome, usa o nome do arquivo
            if (edtNomeDocumento.getText().isEmpty()) {
                edtNomeDocumento.setText(this.arquivoSelecionado.getName());
            }
        }
    }//GEN-LAST:event_btnSelecionarActionPerformed

    private void btnSalvarDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarDocumentoActionPerformed
        String nome = edtNomeDocumento.getText();
        String categoria = (String) cbCategoriaDocumento.getSelectedItem();
        
        // Guard Clauses (Validação defensiva)
        if (this.projetoVinculado == null) {
            JOptionPane.showMessageDialog(this, "Erro crítico: Projeto não vinculado.", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (this.arquivoSelecionado == null) {
             JOptionPane.showMessageDialog(this, "Por favor, selecione um arquivo.", "Aviso", JOptionPane.WARNING_MESSAGE);
             return;
        }

        boolean sucesso = controller.salvarDocumento(nome, categoria, arquivoSelecionado, projetoVinculado);
        
        if (sucesso) {
            JOptionPane.showMessageDialog(this, "Documento anexado com sucesso!");
            this.dispose(); 
        }
    }//GEN-LAST:event_btnSalvarDocumentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                DlgCadastroDocumento dialog = new DlgCadastroDocumento(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvarDocumento;
    private javax.swing.JButton btnSelecionar;
    private javax.swing.JComboBox<String> cbCategoriaDocumento;
    private javax.swing.JTextField edtCaminhoArquivo;
    private javax.swing.JTextField edtNomeDocumento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
