/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view.screens.dialogs;
import controller.ClienteController;
import javax.swing.JOptionPane;
/**
 *
 * @author Viktin
 */
public class DlgCadastroCliente extends javax.swing.JDialog {
    private final ClienteController controller;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DlgCadastroCliente.class.getName());

    /**
     * Creates new form DlgCadastroCliente
     */
    public DlgCadastroCliente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        // 2. Inicializa o Controller passando esta tela
        this.controller = new ClienteController(this);
        
        // Centraliza a janela
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel16 = new javax.swing.JLabel();
        edtCidade = new javax.swing.JTextField();
        edtCep = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        edtNomeCliente = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        edtEmailCliente = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        edtCpfCliente = new javax.swing.JTextField();
        edtLougradouroCliente = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        edtBairroCliente = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        edtNumeroCliente = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        edtCidadeCliente = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        edtCepCliente = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();

        jLabel16.setText("Cidade");

        edtCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtCidadeActionPerformed(evt);
            }
        });

        edtCep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtCepActionPerformed(evt);
            }
        });

        jLabel15.setText("Cep");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        edtNomeCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtNomeClienteActionPerformed(evt);
            }
        });
        jPanel1.add(edtNomeCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 280, -1));

        jLabel8.setText("Nome do Cliente");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 480, 130, 30));

        edtEmailCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtEmailClienteActionPerformed(evt);
            }
        });
        jPanel1.add(edtEmailCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 280, -1));

        jLabel9.setText("E-mail");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel10.setText("CPF");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        edtCpfCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtCpfClienteActionPerformed(evt);
            }
        });
        jPanel1.add(edtCpfCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 280, -1));

        edtLougradouroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtLougradouroClienteActionPerformed(evt);
            }
        });
        jPanel1.add(edtLougradouroCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 280, -1));

        jLabel11.setText("Logradouro");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        edtBairroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtBairroClienteActionPerformed(evt);
            }
        });
        jPanel1.add(edtBairroCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 280, -1));

        jLabel12.setText("Bairro");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, -1));

        edtNumeroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtNumeroClienteActionPerformed(evt);
            }
        });
        jPanel1.add(edtNumeroCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 280, -1));

        jLabel13.setText("Numero");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, -1, -1));

        edtCidadeCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtCidadeClienteActionPerformed(evt);
            }
        });
        jPanel1.add(edtCidadeCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 280, 30));

        jLabel17.setText("Cidade");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        edtCepCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtCepClienteActionPerformed(evt);
            }
        });
        jPanel1.add(edtCepCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 280, 30));

        jLabel18.setText("Cep");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 549, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        controller.cadastrarCliente();
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void edtNomeClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtNomeClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtNomeClienteActionPerformed

    private void edtEmailClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtEmailClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtEmailClienteActionPerformed

    private void edtCpfClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtCpfClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtCpfClienteActionPerformed

    private void edtLougradouroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtLougradouroClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtLougradouroClienteActionPerformed

    private void edtBairroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtBairroClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtBairroClienteActionPerformed

    private void edtNumeroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtNumeroClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtNumeroClienteActionPerformed

    private void edtCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtCidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtCidadeActionPerformed

    private void edtCepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtCepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtCepActionPerformed

    private void edtCidadeClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtCidadeClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtCidadeClienteActionPerformed

    private void edtCepClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtCepClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtCepClienteActionPerformed
    
    public String getNome() {
        return edtNomeCliente.getText();
    }

    public String getEmail() {
        return edtEmailCliente.getText();
    }

    public String getCpf() {
        return edtCpfCliente.getText();
    }

    public String getLogradouro() {
        return edtLougradouroCliente.getText();
    }
    
    public String getCidade() {
        return edtCidadeCliente.getText();
    }
    
    public String getCep() {
        return edtCepCliente.getText();
    }
    
    public String getBairro() {
        return edtBairroCliente.getText();
    }

    public String getNumero() {
        return edtNumeroCliente.getText();
    }
    
    public void exibeMensagem(String msg) {
        JOptionPane.showMessageDialog(this, msg);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                DlgCadastroCliente dialog = new DlgCadastroCliente(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvar;
    private javax.swing.JTextField edtBairroCliente;
    private javax.swing.JTextField edtCep;
    private javax.swing.JTextField edtCepCliente;
    private javax.swing.JTextField edtCidade;
    private javax.swing.JTextField edtCidadeCliente;
    private javax.swing.JTextField edtCpfCliente;
    private javax.swing.JTextField edtEmailCliente;
    private javax.swing.JTextField edtLougradouroCliente;
    private javax.swing.JTextField edtNomeCliente;
    private javax.swing.JTextField edtNumeroCliente;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
