/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view.screens.dialogs;
import model.entities.Projeto;
import java.time.format.DateTimeFormatter;
import java.text.NumberFormat;
import java.util.Locale;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import javax.swing.JOptionPane;
import model.dao.ProjetoDAO;
/**
 *
 * @author Viktin
 */
public class DlgVisualizarProjeto extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DlgVisualizarProjeto.class.getName());
    private Projeto projetoAtual;
    /**
     * Creates new form DlgVisualizarProjeto
     */
    public DlgVisualizarProjeto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
    }
    
    public void setProjeto(Projeto p) {
        if (p == null) return;
        this.projetoAtual = p;
        // Formata datas
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        String inicio = (p.getDataInicio() != null) ? dtf.format(p.getDataInicio()) : "-";
        String fim = (p.getDataPrevisao() != null) ? dtf.format(p.getDataPrevisao()) : "-";
        
        // Preenche os Labels (Supondo que você criou lblNome, lblCliente, etc.)
        lblNomeProjeto.setText(p.getNome());
        lblNomeCliente.setText((p.getCliente() != null) ? p.getCliente().getNome() : "Sem Cliente");
        lblStatus.setText((p.getStatus() != null) ? p.getStatus() : "-");
        lblDataInicio.setText(inicio);
        lblPrevisao.setText(fim);
        Double valor = p.getOrcamento();
        if (valor != null) {
            // Cria um formatador para o Brasil (pt-BR)
            NumberFormat nf = NumberFormat.getCurrencyInstance(new Locale("pt", "BR"));
            lblOrcamento.setText(nf.format(valor)); // Exibe: R$ 30.232,00
        } else {
            lblOrcamento.setText("R$ 0,00");
        }
        // Se tiver descrição
        jTDescricao.setEditable(false);
        jTDescricao.setLineWrap(true); 
        jTDescricao.setWrapStyleWord(true);
        jTDescricao.setText(p.getDescricao());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblNomeCliente = new javax.swing.JLabel();
        lblNomeProjeto = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblDataInicio = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblPrevisao = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblOrcamento = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTDescricao = new javax.swing.JTextArea();
        bntEditar = new javax.swing.JButton();
        btnExcluirProjeto = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNomeCliente.setText("Victor Emmanuel");
        jPanel1.add(lblNomeCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 230, -1));

        lblNomeProjeto.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblNomeProjeto.setText("Casas Duplas");
        jPanel1.add(lblNomeProjeto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 240, -1));

        jLabel3.setText("Cliente:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));
        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 260, -1, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Informações do Projeto");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel7.setText("Status:");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, -1, -1));

        lblStatus.setText("Status");
        jPanel3.add(lblStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 120, -1));

        jLabel9.setText("Descrição:");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jLabel8.setText("Data de Início:");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        lblDataInicio.setText("01/12/2023");
        jPanel3.add(lblDataInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, -1, -1));

        jLabel6.setText("Previsão de fim:");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, -1, -1));

        lblPrevisao.setText("01/12/2024");
        jPanel3.add(lblPrevisao, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, -1, -1));

        jLabel10.setText("Orçamento:");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        lblOrcamento.setText("30,232");
        jPanel3.add(lblOrcamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 100, -1));

        jTDescricao.setColumns(20);
        jTDescricao.setRows(5);
        jScrollPane1.setViewportView(jTDescricao);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 900, 190));

        bntEditar.setText("Editar");
        bntEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntEditarActionPerformed(evt);
            }
        });
        jPanel3.add(bntEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 30, 110, -1));

        btnExcluirProjeto.setText("Excluir Projeto");
        btnExcluirProjeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirProjetoActionPerformed(evt);
            }
        });
        jPanel3.add(btnExcluirProjeto, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 30, 130, -1));

        jTabbedPane2.addTab("Visão Geral", jPanel3);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 335, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Documentos", jPanel2);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 335, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Visualizador 3D", jPanel4);

        jPanel1.add(jTabbedPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 1000, 370));
        jTabbedPane2.getAccessibleContext().setAccessibleName("Visão Geral");

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntEditarActionPerformed
        DlgCadastroProjetos dlg = new DlgCadastroProjetos(null, true);
        
        // 2. Passa o projeto atual para a tela de cadastro preencher os campos
        dlg.setProjetoParaEdicao(this.projetoAtual);
        
        // 3. Centraliza e Exibe
        dlg.setLocationRelativeTo(null);
        dlg.setVisible(true);
        
        // 4. ATUALIZAR A TELA DE VISUALIZAÇÃO (Pós-Edição)
        // Quando o 'dlg' fecha (após salvar), o código continua aqui.
        // O objeto 'this.projetoAtual' foi modificado na memória pelo Hibernate/Java.
        // Chamamos o setProjeto de novo para atualizar os Labels com os novos dados.
        this.setProjeto(this.projetoAtual);
    }//GEN-LAST:event_bntEditarActionPerformed

    private void btnExcluirProjetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirProjetoActionPerformed
        if (this.projetoAtual == null || this.projetoAtual.getId() == null) {
            JOptionPane.showMessageDialog(this, "Erro: Nenhum projeto selecionado.");
            return;
        }

        // 2. Confirmação do Usuário
        int confirmacao = JOptionPane.showConfirmDialog(
            this, 
            "Tem certeza que deseja EXCLUIR o projeto '" + projetoAtual.getNome() + "'?\nEssa ação não pode ser desfeita.", 
            "Excluir Projeto", 
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE
        );

        // Se o usuário clicou em SIM (YES_OPTION = 0)
        if (confirmacao == JOptionPane.YES_OPTION) {
            try {
                // 3. Chama o DAO para remover
                ProjetoDAO dao = new ProjetoDAO();
                dao.remover(projetoAtual.getId());
                
                JOptionPane.showMessageDialog(this, "Projeto excluído com sucesso!");
                
                // 4. Fecha a janela de detalhes, pois o projeto sumiu
                this.dispose();
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Erro ao excluir: " + e.getMessage());
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnExcluirProjetoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                DlgVisualizarProjeto dialog = new DlgVisualizarProjeto(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntEditar;
    private javax.swing.JButton btnExcluirProjeto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTDescricao;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JLabel lblDataInicio;
    private javax.swing.JLabel lblNomeCliente;
    private javax.swing.JLabel lblNomeProjeto;
    private javax.swing.JLabel lblOrcamento;
    private javax.swing.JLabel lblPrevisao;
    private javax.swing.JLabel lblStatus;
    // End of variables declaration//GEN-END:variables
}
