/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view.screens.dialogs.Gestor;

import controller.DespesaController;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import model.entities.Projeto;

/**
 * @author Viktin
 */
public class DlgCadastroDespesa extends javax.swing.JDialog {

    private final DespesaController controller;
    private Projeto projetoVinculado;
    
    // Logger padrão para debug de UI
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DlgCadastroDespesa.class.getName());

    public DlgCadastroDespesa(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        
        this.controller = new DespesaController();
        
    }
    
    public void setProjetoVinculado(Projeto p) {
        this.projetoVinculado = p;
        if (p != null) {
            this.setTitle("Nova Despesa - Projeto: " + p.getNome());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        edtDescricaoDespesa = new javax.swing.JTextField();
        edtValorDespesa = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        edtFornecedorDespesa = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        edtDataDespesa = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        cbCategoria = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cbFormaPag = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        cbStatusDespesa = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTObservacoes = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        btnSalvarDespesa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Descrição:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        edtDescricaoDespesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtDescricaoDespesaActionPerformed(evt);
            }
        });
        getContentPane().add(edtDescricaoDespesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 340, -1));

        edtValorDespesa.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        edtValorDespesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtValorDespesaActionPerformed(evt);
            }
        });
        getContentPane().add(edtValorDespesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 160, -1));

        jLabel4.setText("Valor (R$):");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        edtFornecedorDespesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtFornecedorDespesaActionPerformed(evt);
            }
        });
        getContentPane().add(edtFornecedorDespesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 340, -1));

        jLabel2.setText("Categoria");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        edtDataDespesa.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        edtDataDespesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtDataDespesaActionPerformed(evt);
            }
        });
        getContentPane().add(edtDataDespesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 160, -1));

        jLabel3.setText("Fornecedor:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        cbCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Material", "Mão de Obra", "Transporte", "Taxas", "Alimentação", "Outros" }));
        cbCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCategoriaActionPerformed(evt);
            }
        });
        getContentPane().add(cbCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 160, -1));

        jLabel5.setText("Data do Gasto");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, -1, -1));

        jLabel6.setText("Forma de Pagamento");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, -1, -1));

        cbFormaPag.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pix", "Cartão de Crédito", "Cartão de Débito", "Dinheiro", "Boleto", "Transferência" }));
        getContentPane().add(cbFormaPag, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 160, -1));

        jLabel7.setText("Observaçoes:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        cbStatusDespesa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pago", "Pendente" }));
        getContentPane().add(cbStatusDespesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 160, -1));

        jTObservacoes.setColumns(20);
        jTObservacoes.setRows(5);
        jScrollPane1.setViewportView(jTObservacoes);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 340, 90));

        jLabel8.setText("Status");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        btnSalvarDespesa.setText("Salvar");
        btnSalvarDespesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarDespesaActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalvarDespesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 390, 110, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarDespesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarDespesaActionPerformed
            boolean sucesso = controller.salvarDespesa(
                edtDescricaoDespesa.getText(), 
                edtValorDespesa.getText(), 
                (String) cbCategoria.getSelectedItem(), 
                edtDataDespesa.getText(), 
                edtFornecedorDespesa.getText(), 
                (String) cbStatusDespesa.getSelectedItem(), 
                (String) cbFormaPag.getSelectedItem(), 
                jTObservacoes.getText(), 
                this.projetoVinculado
        );

        if (sucesso) {
            JOptionPane.showMessageDialog(this, "Despesa salva com sucesso!");
            this.dispose();
        }
    }//GEN-LAST:event_btnSalvarDespesaActionPerformed

    private void edtDescricaoDespesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtDescricaoDespesaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtDescricaoDespesaActionPerformed

    private void edtValorDespesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtValorDespesaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtValorDespesaActionPerformed

    private void edtDataDespesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtDataDespesaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtDataDespesaActionPerformed

    private void edtFornecedorDespesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtFornecedorDespesaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtFornecedorDespesaActionPerformed

    private void cbCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbCategoriaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                DlgCadastroDespesa dialog = new DlgCadastroDespesa(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvarDespesa;
    private javax.swing.JComboBox<String> cbCategoria;
    private javax.swing.JComboBox<String> cbFormaPag;
    private javax.swing.JComboBox<String> cbStatusDespesa;
    private javax.swing.JFormattedTextField edtDataDespesa;
    private javax.swing.JTextField edtDescricaoDespesa;
    private javax.swing.JTextField edtFornecedorDespesa;
    private javax.swing.JFormattedTextField edtValorDespesa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTObservacoes;
    // End of variables declaration//GEN-END:variables
}
