/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view.screens.dialogs.Gestor;

import controller.TerrenoController;
import javax.swing.JOptionPane;
import model.entities.Projeto; 
import model.entities.Terreno;

/**
 * @author Viktin
 */
public class DlgCadastroTerreno extends javax.swing.JDialog {
    
    private final TerrenoController controller;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DlgCadastroTerreno.class.getName());

    public DlgCadastroTerreno(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        // Inicializa o Controller passando a View (this)
        this.controller = new TerrenoController(this);
        this.setLocationRelativeTo(null);
    }
    
    // --- Métodos de Negócio ---
    
    public void carregarTerreno(Terreno t) {
        // Delega para o controller preencher os campos
        controller.preencherTelaParaEdicao(t);
    }
    
    public void setProjetoVinculado(Projeto p) {
        controller.setProjetoPai(p);
    }
    
    // Dados Básicos
    public void setTextoNome(String texto) { edtNomeTerreno.setText(texto); }
    public void setTextoReferencia(String texto) { edtReferenciaTerreno.setText(texto); }
    public void setTextoDescricao(String texto) { edtDescricaoTerreno.setText(texto); }
    public void setTextoValor(String texto) { edtValorTerreno.setText(texto); }
    public void setTextoArea(String texto) { edtAreaTotal.setText(texto); }

    // Endereço
    public void setTextoCep(String texto) { edtCepTerreno.setText(texto); }
    public void setTextoCidade(String texto) { edtCidadeTerreno.setText(texto); }
    public void setTextoLogradouro(String texto) { estLogradouroTerreno.setText(texto); } // O nome da variavel ficou 'est' no design
    public void setTextoBairro(String texto) { edtBairroTerreno.setText(texto); }
    public void setTextoNumero(String texto) { edtNumeroTerreno.setText(texto); }

    // Dados Técnicos
    public void setTextoCoeficiente(String texto) { edtCoeficienteTerreno.setText(texto); }
    public void setTextoTaxa(String texto) { edtTaxaTerreno.setText(texto); }
    public void setTextoGabarito(String texto) { edtGabaritoTerreno.setText(texto); }
    
    // Combos
    public void setSelecionadoTopografia(String valor) { cbTopografia.setSelectedItem(valor); }
    public void setSelecionadoTipo(String valor) { cbTipo.setSelectedItem(valor); }

    // GETTERS 
    public String getNome() { return edtNomeTerreno.getText(); }
    public String getReferencia() { return edtReferenciaTerreno.getText(); }
    public String getAreaTotal() { return edtAreaTotal.getText(); }
    public String getValorCompra() { return edtValorTerreno.getText(); }
    public String getDescricao() { return edtDescricaoTerreno.getText(); }
    
    public String getTopografia() { return (String) cbTopografia.getSelectedItem(); }
    public String getTipoSolo() { return (String) cbTipo.getSelectedItem(); }
    
    public String getCoeficienteAproveitamento() { return edtCoeficienteTerreno.getText(); }
    public String getTaxaOcupacao() { return edtTaxaTerreno.getText(); }
    public String getGabaritoAltura() { return edtGabaritoTerreno.getText(); }
    
    public String getCep() { return edtCepTerreno.getText(); }
    public String getCidade() { return edtCidadeTerreno.getText(); }
    public String getLogradouro() { return estLogradouroTerreno.getText(); }
    public String getBairro() { return edtBairroTerreno.getText(); }
    public String getNumero() { return edtNumeroTerreno.getText(); }
    
    // Mensagens
    public void exibeMensagem(String msg) {
        JOptionPane.showMessageDialog(this, msg);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSalvar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        edtNomeTerreno = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        edtDescricaoTerreno = new javax.swing.JTextArea();
        edtCidadeTerreno = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        estLogradouroTerreno = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        edtBairroTerreno = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        edtNumeroTerreno = new javax.swing.JTextField();
        edtCepTerreno = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        edtAreaTotal = new javax.swing.JFormattedTextField();
        jLabel14 = new javax.swing.JLabel();
        cbTopografia = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        cbTipo = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        edtReferenciaTerreno = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        edtCoeficienteTerreno = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        edtGabaritoTerreno = new javax.swing.JTextField();
        edtTaxaTerreno = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        edtValorTerreno = new javax.swing.JFormattedTextField();
        jLabel21 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        edtNomeTerreno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtNomeTerrenoActionPerformed(evt);
            }
        });
        jPanel1.add(edtNomeTerreno, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 280, -1));

        jLabel8.setText("Nome do Terreno:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jLabel7.setText("Descrição / Observações:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 140, -1));

        edtDescricaoTerreno.setColumns(20);
        edtDescricaoTerreno.setRows(5);
        jScrollPane1.setViewportView(edtDescricaoTerreno);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 590, 150));

        edtCidadeTerreno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtCidadeTerrenoActionPerformed(evt);
            }
        });
        jPanel1.add(edtCidadeTerreno, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 280, -1));

        jLabel9.setText("Cidade");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        estLogradouroTerreno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estLogradouroTerrenoActionPerformed(evt);
            }
        });
        jPanel1.add(estLogradouroTerreno, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 280, -1));

        jLabel10.setText("Logradouro");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel11.setText("Bairro");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        edtBairroTerreno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtBairroTerrenoActionPerformed(evt);
            }
        });
        jPanel1.add(edtBairroTerreno, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 280, -1));

        jLabel12.setText("Número");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        edtNumeroTerreno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtNumeroTerrenoActionPerformed(evt);
            }
        });
        jPanel1.add(edtNumeroTerreno, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 280, -1));

        edtCepTerreno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtCepTerrenoActionPerformed(evt);
            }
        });
        jPanel1.add(edtCepTerreno, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 280, -1));

        jLabel13.setText("CEP:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        edtAreaTotal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        jPanel1.add(edtAreaTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, 130, -1));

        jLabel14.setText("Área Total (m²):");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, -1, -1));

        cbTopografia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Plano", "Aclive", "Declive", "Irregular" }));
        cbTopografia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTopografiaActionPerformed(evt);
            }
        });
        jPanel1.add(cbTopografia, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, 130, -1));

        jLabel15.setText("Topografia:");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, -1, -1));

        cbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Arenoso", "Argiloso", "Siltoso", "Humífero", "Outro" }));
        cbTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoActionPerformed(evt);
            }
        });
        jPanel1.add(cbTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 110, 130, -1));

        jLabel16.setText("Tipo de Solo:");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 90, -1, -1));

        edtReferenciaTerreno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtReferenciaTerrenoActionPerformed(evt);
            }
        });
        jPanel1.add(edtReferenciaTerreno, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, 280, -1));

        jLabel17.setText("Referência:");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, -1, -1));

        edtCoeficienteTerreno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtCoeficienteTerrenoActionPerformed(evt);
            }
        });
        jPanel1.add(edtCoeficienteTerreno, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, 280, -1));

        jLabel18.setText("Coeficiente de Aproveitamento (C.A.):");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, -1, -1));

        jLabel19.setText("Gabarito de Altura (m):");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, -1, -1));

        edtGabaritoTerreno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtGabaritoTerrenoActionPerformed(evt);
            }
        });
        jPanel1.add(edtGabaritoTerreno, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 310, 280, -1));

        edtTaxaTerreno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtTaxaTerrenoActionPerformed(evt);
            }
        });
        jPanel1.add(edtTaxaTerreno, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, 280, -1));

        jLabel20.setText("Taxa de Ocupação (%):");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, -1, -1));

        edtValorTerreno.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        jPanel1.add(edtValorTerreno, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 160, 130, -1));

        jLabel21.setText("Valor do Terreno (R$):");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 140, -1, -1));

        jButton1.setText("Salvar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 540, 150, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void edtNomeTerrenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtNomeTerrenoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtNomeTerrenoActionPerformed

    private void edtCidadeTerrenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtCidadeTerrenoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtCidadeTerrenoActionPerformed

    private void estLogradouroTerrenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estLogradouroTerrenoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estLogradouroTerrenoActionPerformed

    private void edtBairroTerrenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtBairroTerrenoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtBairroTerrenoActionPerformed

    private void edtNumeroTerrenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtNumeroTerrenoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtNumeroTerrenoActionPerformed

    private void edtCepTerrenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtCepTerrenoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtCepTerrenoActionPerformed

    private void cbTopografiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTopografiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTopografiaActionPerformed

    private void cbTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTipoActionPerformed

    private void edtReferenciaTerrenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtReferenciaTerrenoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtReferenciaTerrenoActionPerformed

    private void edtCoeficienteTerrenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtCoeficienteTerrenoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtCoeficienteTerrenoActionPerformed

    private void edtGabaritoTerrenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtGabaritoTerrenoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtGabaritoTerrenoActionPerformed

    private void edtTaxaTerrenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtTaxaTerrenoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtTaxaTerrenoActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        controller.salvarTerreno();
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        controller.salvarTerreno();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                DlgCadastroTerreno dialog = new DlgCadastroTerreno(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cbTipo;
    private javax.swing.JComboBox<String> cbTopografia;
    private javax.swing.JFormattedTextField edtAreaTotal;
    private javax.swing.JTextField edtBairroTerreno;
    private javax.swing.JTextField edtCepTerreno;
    private javax.swing.JTextField edtCidadeTerreno;
    private javax.swing.JTextField edtCoeficienteTerreno;
    private javax.swing.JTextArea edtDescricaoTerreno;
    private javax.swing.JTextField edtGabaritoTerreno;
    private javax.swing.JTextField edtNomeTerreno;
    private javax.swing.JTextField edtNumeroTerreno;
    private javax.swing.JTextField edtReferenciaTerreno;
    private javax.swing.JTextField edtTaxaTerreno;
    private javax.swing.JFormattedTextField edtValorTerreno;
    private javax.swing.JTextField estLogradouroTerreno;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
